app:
  host: 0.0.0.0
  port: 4141
  jwtKey: secretKey

database:
  host: 0.0.0.0
  port: 5432
  username: root
  password: password
  name: chotodb
  maxIdleConnections: 10
  maxActiveConnections: 30
  maxConnectionLifetime: 10