version: '3.1'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: chotodb
      POSTGRES_PASSWORD: sadat@642
      POSTGRES_USER: root
    volumes:
      - "pgvol:/var/lib/postgresql/data"
  pgAdmin:
    restart: always
    image: dpage/pgadmin4
    ports:
        - "8001:80"
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: 1234
    volumes:
        - pgadmin:/var/lib/pgadmin
  
volumes:
  pgvol:
  pgadmin: