version: '3.1'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: chotodb
      POSTGRES_PASSWORD: sadat@642
      POSTGRES_USER: root
    volumes:
      - "pgvol:/var/lib/postgresql/data"
  
volumes:
  pgvol: