version: '3.1'

services:
  choto-backend:
    image: caffeines/choto:rc
    # command: ["serve"]
    restart: always
    ports:
      - 4521:4521
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: chotodb
      POSTGRES_PASSWORD: sadat@642
      POSTGRES_USER: root
    volumes:
      - "pgvol:/var/lib/postgresql/data"
  adminer:
    image: adminer
    container_name: choto_adminer
    restart: always
    ports:
      - 8001:8080
volumes:
  pgvol: